// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchPoint.Data.DBContext;

#nullable disable

namespace SearchPoint.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231105204513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchPoint.Data.Entities.Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BottomLeftX")
                        .HasColumnType("float");

                    b.Property<double>("BottomLeftY")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TopRightX")
                        .HasColumnType("float");

                    b.Property<double>("TopRightY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BottomLeftX = 436.0,
                            BottomLeftY = 48.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 206, DateTimeKind.Utc).AddTicks(9930),
                            TopRightX = 458.0,
                            TopRightY = 56.0
                        },
                        new
                        {
                            Id = 2,
                            BottomLeftX = 210.0,
                            BottomLeftY = 449.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 206, DateTimeKind.Utc).AddTicks(9960),
                            TopRightX = 222.0,
                            TopRightY = 471.0
                        },
                        new
                        {
                            Id = 3,
                            BottomLeftX = 180.0,
                            BottomLeftY = 226.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 206, DateTimeKind.Utc).AddTicks(9990),
                            TopRightX = 209.0,
                            TopRightY = 250.0
                        },
                        new
                        {
                            Id = 4,
                            BottomLeftX = 162.0,
                            BottomLeftY = 432.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(10),
                            TopRightX = 168.0,
                            TopRightY = 443.0
                        },
                        new
                        {
                            Id = 5,
                            BottomLeftX = 128.0,
                            BottomLeftY = 488.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(30),
                            TopRightX = 136.0,
                            TopRightY = 499.0
                        },
                        new
                        {
                            Id = 6,
                            BottomLeftX = 217.0,
                            BottomLeftY = 481.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(60),
                            TopRightX = 242.0,
                            TopRightY = 506.0
                        },
                        new
                        {
                            Id = 7,
                            BottomLeftX = 235.0,
                            BottomLeftY = 32.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(80),
                            TopRightX = 257.0,
                            TopRightY = 49.0
                        },
                        new
                        {
                            Id = 8,
                            BottomLeftX = 271.0,
                            BottomLeftY = 466.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(110),
                            TopRightX = 287.0,
                            TopRightY = 486.0
                        },
                        new
                        {
                            Id = 9,
                            BottomLeftX = 170.0,
                            BottomLeftY = 309.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(130),
                            TopRightX = 175.0,
                            TopRightY = 318.0
                        },
                        new
                        {
                            Id = 10,
                            BottomLeftX = 277.0,
                            BottomLeftY = 154.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(160),
                            TopRightX = 293.0,
                            TopRightY = 161.0
                        },
                        new
                        {
                            Id = 11,
                            BottomLeftX = 174.0,
                            BottomLeftY = 443.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(180),
                            TopRightX = 185.0,
                            TopRightY = 470.0
                        },
                        new
                        {
                            Id = 12,
                            BottomLeftX = 241.0,
                            BottomLeftY = 46.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(200),
                            TopRightX = 258.0,
                            TopRightY = 55.0
                        },
                        new
                        {
                            Id = 13,
                            BottomLeftX = 395.0,
                            BottomLeftY = 75.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(230),
                            TopRightX = 423.0,
                            TopRightY = 88.0
                        },
                        new
                        {
                            Id = 14,
                            BottomLeftX = 399.0,
                            BottomLeftY = 23.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(260),
                            TopRightX = 412.0,
                            TopRightY = 51.0
                        },
                        new
                        {
                            Id = 15,
                            BottomLeftX = 499.0,
                            BottomLeftY = 290.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(280),
                            TopRightX = 511.0,
                            TopRightY = 307.0
                        },
                        new
                        {
                            Id = 16,
                            BottomLeftX = 462.0,
                            BottomLeftY = 121.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(300),
                            TopRightX = 479.0,
                            TopRightY = 138.0
                        },
                        new
                        {
                            Id = 17,
                            BottomLeftX = 393.0,
                            BottomLeftY = 257.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(330),
                            TopRightX = 417.0,
                            TopRightY = 279.0
                        },
                        new
                        {
                            Id = 18,
                            BottomLeftX = 473.0,
                            BottomLeftY = 224.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(350),
                            TopRightX = 487.0,
                            TopRightY = 232.0
                        },
                        new
                        {
                            Id = 19,
                            BottomLeftX = 192.0,
                            BottomLeftY = 188.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(380),
                            TopRightX = 221.0,
                            TopRightY = 193.0
                        },
                        new
                        {
                            Id = 20,
                            BottomLeftX = 347.0,
                            BottomLeftY = 187.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(400),
                            TopRightX = 357.0,
                            TopRightY = 200.0
                        },
                        new
                        {
                            Id = 21,
                            BottomLeftX = 221.0,
                            BottomLeftY = 70.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(430),
                            TopRightX = 230.0,
                            TopRightY = 94.0
                        },
                        new
                        {
                            Id = 22,
                            BottomLeftX = 214.0,
                            BottomLeftY = 225.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(450),
                            TopRightX = 222.0,
                            TopRightY = 249.0
                        },
                        new
                        {
                            Id = 23,
                            BottomLeftX = 143.0,
                            BottomLeftY = 130.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(470),
                            TopRightX = 148.0,
                            TopRightY = 153.0
                        },
                        new
                        {
                            Id = 24,
                            BottomLeftX = 64.0,
                            BottomLeftY = 486.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(500),
                            TopRightX = 75.0,
                            TopRightY = 504.0
                        },
                        new
                        {
                            Id = 25,
                            BottomLeftX = 337.0,
                            BottomLeftY = 226.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(520),
                            TopRightX = 352.0,
                            TopRightY = 236.0
                        },
                        new
                        {
                            Id = 26,
                            BottomLeftX = 243.0,
                            BottomLeftY = 470.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(550),
                            TopRightX = 257.0,
                            TopRightY = 493.0
                        },
                        new
                        {
                            Id = 27,
                            BottomLeftX = 97.0,
                            BottomLeftY = 79.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(570),
                            TopRightX = 105.0,
                            TopRightY = 108.0
                        },
                        new
                        {
                            Id = 28,
                            BottomLeftX = 103.0,
                            BottomLeftY = 266.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(590),
                            TopRightX = 124.0,
                            TopRightY = 273.0
                        },
                        new
                        {
                            Id = 29,
                            BottomLeftX = 52.0,
                            BottomLeftY = 82.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(620),
                            TopRightX = 79.0,
                            TopRightY = 95.0
                        },
                        new
                        {
                            Id = 30,
                            BottomLeftX = 402.0,
                            BottomLeftY = 77.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(640),
                            TopRightX = 414.0,
                            TopRightY = 104.0
                        },
                        new
                        {
                            Id = 31,
                            BottomLeftX = 199.0,
                            BottomLeftY = 346.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(670),
                            TopRightX = 227.0,
                            TopRightY = 358.0
                        },
                        new
                        {
                            Id = 32,
                            BottomLeftX = 125.0,
                            BottomLeftY = 196.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(690),
                            TopRightX = 139.0,
                            TopRightY = 203.0
                        },
                        new
                        {
                            Id = 33,
                            BottomLeftX = 249.0,
                            BottomLeftY = 128.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(710),
                            TopRightX = 274.0,
                            TopRightY = 147.0
                        },
                        new
                        {
                            Id = 34,
                            BottomLeftX = 353.0,
                            BottomLeftY = 341.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(760),
                            TopRightX = 364.0,
                            TopRightY = 352.0
                        },
                        new
                        {
                            Id = 35,
                            BottomLeftX = 335.0,
                            BottomLeftY = 284.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(780),
                            TopRightX = 348.0,
                            TopRightY = 302.0
                        },
                        new
                        {
                            Id = 36,
                            BottomLeftX = 168.0,
                            BottomLeftY = 446.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(810),
                            TopRightX = 173.0,
                            TopRightY = 452.0
                        },
                        new
                        {
                            Id = 37,
                            BottomLeftX = 381.0,
                            BottomLeftY = 285.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(830),
                            TopRightX = 410.0,
                            TopRightY = 306.0
                        },
                        new
                        {
                            Id = 38,
                            BottomLeftX = 225.0,
                            BottomLeftY = 3.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(860),
                            TopRightX = 246.0,
                            TopRightY = 21.0
                        },
                        new
                        {
                            Id = 39,
                            BottomLeftX = 459.0,
                            BottomLeftY = 21.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(880),
                            TopRightX = 470.0,
                            TopRightY = 38.0
                        },
                        new
                        {
                            Id = 40,
                            BottomLeftX = 423.0,
                            BottomLeftY = 232.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(900),
                            TopRightX = 442.0,
                            TopRightY = 244.0
                        },
                        new
                        {
                            Id = 41,
                            BottomLeftX = 196.0,
                            BottomLeftY = 438.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(930),
                            TopRightX = 215.0,
                            TopRightY = 445.0
                        },
                        new
                        {
                            Id = 42,
                            BottomLeftX = 112.0,
                            BottomLeftY = 96.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(950),
                            TopRightX = 120.0,
                            TopRightY = 119.0
                        },
                        new
                        {
                            Id = 43,
                            BottomLeftX = 173.0,
                            BottomLeftY = 233.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(980),
                            TopRightX = 201.0,
                            TopRightY = 238.0
                        },
                        new
                        {
                            Id = 44,
                            BottomLeftX = 31.0,
                            BottomLeftY = 341.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1000),
                            TopRightX = 56.0,
                            TopRightY = 359.0
                        },
                        new
                        {
                            Id = 45,
                            BottomLeftX = 210.0,
                            BottomLeftY = 216.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1020),
                            TopRightX = 220.0,
                            TopRightY = 226.0
                        },
                        new
                        {
                            Id = 46,
                            BottomLeftX = 164.0,
                            BottomLeftY = 80.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1050),
                            TopRightX = 192.0,
                            TopRightY = 107.0
                        },
                        new
                        {
                            Id = 47,
                            BottomLeftX = 96.0,
                            BottomLeftY = 352.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1070),
                            TopRightX = 104.0,
                            TopRightY = 358.0
                        },
                        new
                        {
                            Id = 48,
                            BottomLeftX = 323.0,
                            BottomLeftY = 98.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1100),
                            TopRightX = 346.0,
                            TopRightY = 103.0
                        },
                        new
                        {
                            Id = 49,
                            BottomLeftX = 416.0,
                            BottomLeftY = 36.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1120),
                            TopRightX = 429.0,
                            TopRightY = 46.0
                        },
                        new
                        {
                            Id = 50,
                            BottomLeftX = 311.0,
                            BottomLeftY = 313.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1140),
                            TopRightX = 337.0,
                            TopRightY = 331.0
                        },
                        new
                        {
                            Id = 51,
                            BottomLeftX = 104.0,
                            BottomLeftY = 143.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1170),
                            TopRightX = 120.0,
                            TopRightY = 156.0
                        },
                        new
                        {
                            Id = 52,
                            BottomLeftX = 241.0,
                            BottomLeftY = 88.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1190),
                            TopRightX = 248.0,
                            TopRightY = 95.0
                        },
                        new
                        {
                            Id = 53,
                            BottomLeftX = 356.0,
                            BottomLeftY = 96.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1220),
                            TopRightX = 367.0,
                            TopRightY = 108.0
                        },
                        new
                        {
                            Id = 54,
                            BottomLeftX = 256.0,
                            BottomLeftY = 455.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1240),
                            TopRightX = 285.0,
                            TopRightY = 473.0
                        },
                        new
                        {
                            Id = 55,
                            BottomLeftX = 39.0,
                            BottomLeftY = 93.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1260),
                            TopRightX = 56.0,
                            TopRightY = 109.0
                        },
                        new
                        {
                            Id = 56,
                            BottomLeftX = 76.0,
                            BottomLeftY = 495.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1290),
                            TopRightX = 96.0,
                            TopRightY = 511.0
                        },
                        new
                        {
                            Id = 57,
                            BottomLeftX = 494.0,
                            BottomLeftY = 134.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1320),
                            TopRightX = 504.0,
                            TopRightY = 150.0
                        },
                        new
                        {
                            Id = 58,
                            BottomLeftX = 2.0,
                            BottomLeftY = 263.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1340),
                            TopRightX = 22.0,
                            TopRightY = 273.0
                        },
                        new
                        {
                            Id = 59,
                            BottomLeftX = 143.0,
                            BottomLeftY = 20.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1360),
                            TopRightX = 154.0,
                            TopRightY = 41.0
                        },
                        new
                        {
                            Id = 60,
                            BottomLeftX = 480.0,
                            BottomLeftY = 100.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1390),
                            TopRightX = 508.0,
                            TopRightY = 107.0
                        },
                        new
                        {
                            Id = 61,
                            BottomLeftX = 59.0,
                            BottomLeftY = 282.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1410),
                            TopRightX = 86.0,
                            TopRightY = 297.0
                        },
                        new
                        {
                            Id = 62,
                            BottomLeftX = 275.0,
                            BottomLeftY = 163.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1440),
                            TopRightX = 304.0,
                            TopRightY = 179.0
                        },
                        new
                        {
                            Id = 63,
                            BottomLeftX = 67.0,
                            BottomLeftY = 76.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1460),
                            TopRightX = 74.0,
                            TopRightY = 103.0
                        },
                        new
                        {
                            Id = 64,
                            BottomLeftX = 301.0,
                            BottomLeftY = 325.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1480),
                            TopRightX = 317.0,
                            TopRightY = 339.0
                        },
                        new
                        {
                            Id = 65,
                            BottomLeftX = 189.0,
                            BottomLeftY = 289.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1510),
                            TopRightX = 211.0,
                            TopRightY = 301.0
                        },
                        new
                        {
                            Id = 66,
                            BottomLeftX = 356.0,
                            BottomLeftY = 121.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1530),
                            TopRightX = 367.0,
                            TopRightY = 131.0
                        },
                        new
                        {
                            Id = 67,
                            BottomLeftX = 491.0,
                            BottomLeftY = 13.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1560),
                            TopRightX = 518.0,
                            TopRightY = 38.0
                        },
                        new
                        {
                            Id = 68,
                            BottomLeftX = 341.0,
                            BottomLeftY = 90.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1580),
                            TopRightX = 358.0,
                            TopRightY = 115.0
                        },
                        new
                        {
                            Id = 69,
                            BottomLeftX = 379.0,
                            BottomLeftY = 283.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1600),
                            TopRightX = 396.0,
                            TopRightY = 305.0
                        },
                        new
                        {
                            Id = 70,
                            BottomLeftX = 454.0,
                            BottomLeftY = 362.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1630),
                            TopRightX = 474.0,
                            TopRightY = 367.0
                        },
                        new
                        {
                            Id = 71,
                            BottomLeftX = 452.0,
                            BottomLeftY = 84.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1650),
                            TopRightX = 477.0,
                            TopRightY = 92.0
                        },
                        new
                        {
                            Id = 72,
                            BottomLeftX = 468.0,
                            BottomLeftY = 351.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1680),
                            TopRightX = 482.0,
                            TopRightY = 364.0
                        },
                        new
                        {
                            Id = 73,
                            BottomLeftX = 464.0,
                            BottomLeftY = 412.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1700),
                            TopRightX = 484.0,
                            TopRightY = 422.0
                        },
                        new
                        {
                            Id = 74,
                            BottomLeftX = 40.0,
                            BottomLeftY = 301.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1720),
                            TopRightX = 58.0,
                            TopRightY = 317.0
                        },
                        new
                        {
                            Id = 75,
                            BottomLeftX = 162.0,
                            BottomLeftY = 61.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1750),
                            TopRightX = 171.0,
                            TopRightY = 79.0
                        },
                        new
                        {
                            Id = 76,
                            BottomLeftX = 8.0,
                            BottomLeftY = 235.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1770),
                            TopRightX = 13.0,
                            TopRightY = 247.0
                        },
                        new
                        {
                            Id = 77,
                            BottomLeftX = 1.0,
                            BottomLeftY = 415.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1820),
                            TopRightX = 24.0,
                            TopRightY = 429.0
                        },
                        new
                        {
                            Id = 78,
                            BottomLeftX = 297.0,
                            BottomLeftY = 343.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1850),
                            TopRightX = 308.0,
                            TopRightY = 348.0
                        },
                        new
                        {
                            Id = 79,
                            BottomLeftX = 458.0,
                            BottomLeftY = 402.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1870),
                            TopRightX = 482.0,
                            TopRightY = 408.0
                        },
                        new
                        {
                            Id = 80,
                            BottomLeftX = 238.0,
                            BottomLeftY = 41.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1900),
                            TopRightX = 264.0,
                            TopRightY = 61.0
                        },
                        new
                        {
                            Id = 81,
                            BottomLeftX = 230.0,
                            BottomLeftY = 30.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1920),
                            TopRightX = 243.0,
                            TopRightY = 57.0
                        },
                        new
                        {
                            Id = 82,
                            BottomLeftX = 30.0,
                            BottomLeftY = 320.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1940),
                            TopRightX = 41.0,
                            TopRightY = 327.0
                        },
                        new
                        {
                            Id = 83,
                            BottomLeftX = 137.0,
                            BottomLeftY = 63.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1970),
                            TopRightX = 148.0,
                            TopRightY = 69.0
                        },
                        new
                        {
                            Id = 84,
                            BottomLeftX = 85.0,
                            BottomLeftY = 155.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(1990),
                            TopRightX = 91.0,
                            TopRightY = 174.0
                        },
                        new
                        {
                            Id = 85,
                            BottomLeftX = 320.0,
                            BottomLeftY = 305.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2020),
                            TopRightX = 330.0,
                            TopRightY = 316.0
                        },
                        new
                        {
                            Id = 86,
                            BottomLeftX = 62.0,
                            BottomLeftY = 278.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2040),
                            TopRightX = 90.0,
                            TopRightY = 307.0
                        },
                        new
                        {
                            Id = 87,
                            BottomLeftX = 103.0,
                            BottomLeftY = 361.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2060),
                            TopRightX = 121.0,
                            TopRightY = 373.0
                        },
                        new
                        {
                            Id = 88,
                            BottomLeftX = 151.0,
                            BottomLeftY = 419.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2090),
                            TopRightX = 165.0,
                            TopRightY = 432.0
                        },
                        new
                        {
                            Id = 89,
                            BottomLeftX = 146.0,
                            BottomLeftY = 236.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2110),
                            TopRightX = 167.0,
                            TopRightY = 260.0
                        },
                        new
                        {
                            Id = 90,
                            BottomLeftX = 350.0,
                            BottomLeftY = 156.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2140),
                            TopRightX = 357.0,
                            TopRightY = 174.0
                        },
                        new
                        {
                            Id = 91,
                            BottomLeftX = 178.0,
                            BottomLeftY = 296.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2160),
                            TopRightX = 187.0,
                            TopRightY = 303.0
                        },
                        new
                        {
                            Id = 92,
                            BottomLeftX = 106.0,
                            BottomLeftY = 311.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2180),
                            TopRightX = 130.0,
                            TopRightY = 320.0
                        },
                        new
                        {
                            Id = 93,
                            BottomLeftX = 118.0,
                            BottomLeftY = 446.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2210),
                            TopRightX = 147.0,
                            TopRightY = 468.0
                        },
                        new
                        {
                            Id = 94,
                            BottomLeftX = 75.0,
                            BottomLeftY = 227.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2230),
                            TopRightX = 91.0,
                            TopRightY = 247.0
                        },
                        new
                        {
                            Id = 95,
                            BottomLeftX = 73.0,
                            BottomLeftY = 64.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2260),
                            TopRightX = 87.0,
                            TopRightY = 81.0
                        },
                        new
                        {
                            Id = 96,
                            BottomLeftX = 214.0,
                            BottomLeftY = 149.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2280),
                            TopRightX = 240.0,
                            TopRightY = 170.0
                        },
                        new
                        {
                            Id = 97,
                            BottomLeftX = 57.0,
                            BottomLeftY = 59.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2300),
                            TopRightX = 77.0,
                            TopRightY = 66.0
                        },
                        new
                        {
                            Id = 98,
                            BottomLeftX = 58.0,
                            BottomLeftY = 178.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2330),
                            TopRightX = 70.0,
                            TopRightY = 186.0
                        },
                        new
                        {
                            Id = 99,
                            BottomLeftX = 384.0,
                            BottomLeftY = 217.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2350),
                            TopRightX = 401.0,
                            TopRightY = 234.0
                        },
                        new
                        {
                            Id = 100,
                            BottomLeftX = 25.0,
                            BottomLeftY = 138.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2380),
                            TopRightX = 43.0,
                            TopRightY = 157.0
                        },
                        new
                        {
                            Id = 101,
                            BottomLeftX = 310.0,
                            BottomLeftY = 274.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2400),
                            TopRightX = 336.0,
                            TopRightY = 302.0
                        },
                        new
                        {
                            Id = 102,
                            BottomLeftX = 10.0,
                            BottomLeftY = 105.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2430),
                            TopRightX = 37.0,
                            TopRightY = 131.0
                        },
                        new
                        {
                            Id = 103,
                            BottomLeftX = 49.0,
                            BottomLeftY = 71.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2450),
                            TopRightX = 74.0,
                            TopRightY = 92.0
                        },
                        new
                        {
                            Id = 104,
                            BottomLeftX = 226.0,
                            BottomLeftY = 292.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2470),
                            TopRightX = 249.0,
                            TopRightY = 311.0
                        },
                        new
                        {
                            Id = 105,
                            BottomLeftX = 78.0,
                            BottomLeftY = 253.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2500),
                            TopRightX = 95.0,
                            TopRightY = 276.0
                        },
                        new
                        {
                            Id = 106,
                            BottomLeftX = 451.0,
                            BottomLeftY = 139.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2520),
                            TopRightX = 457.0,
                            TopRightY = 153.0
                        },
                        new
                        {
                            Id = 107,
                            BottomLeftX = 77.0,
                            BottomLeftY = 388.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2550),
                            TopRightX = 96.0,
                            TopRightY = 400.0
                        },
                        new
                        {
                            Id = 108,
                            BottomLeftX = 189.0,
                            BottomLeftY = 68.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2570),
                            TopRightX = 194.0,
                            TopRightY = 88.0
                        },
                        new
                        {
                            Id = 109,
                            BottomLeftX = 361.0,
                            BottomLeftY = 350.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2590),
                            TopRightX = 371.0,
                            TopRightY = 378.0
                        },
                        new
                        {
                            Id = 110,
                            BottomLeftX = 456.0,
                            BottomLeftY = 323.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2620),
                            TopRightX = 476.0,
                            TopRightY = 333.0
                        },
                        new
                        {
                            Id = 111,
                            BottomLeftX = 339.0,
                            BottomLeftY = 317.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2640),
                            TopRightX = 352.0,
                            TopRightY = 331.0
                        },
                        new
                        {
                            Id = 112,
                            BottomLeftX = 406.0,
                            BottomLeftY = 291.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2670),
                            TopRightX = 417.0,
                            TopRightY = 302.0
                        },
                        new
                        {
                            Id = 113,
                            BottomLeftX = 238.0,
                            BottomLeftY = 17.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2690),
                            TopRightX = 257.0,
                            TopRightY = 25.0
                        },
                        new
                        {
                            Id = 114,
                            BottomLeftX = 262.0,
                            BottomLeftY = 379.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2710),
                            TopRightX = 271.0,
                            TopRightY = 408.0
                        },
                        new
                        {
                            Id = 115,
                            BottomLeftX = 64.0,
                            BottomLeftY = 242.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2740),
                            TopRightX = 88.0,
                            TopRightY = 251.0
                        },
                        new
                        {
                            Id = 116,
                            BottomLeftX = 493.0,
                            BottomLeftY = 253.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2760),
                            TopRightX = 502.0,
                            TopRightY = 264.0
                        },
                        new
                        {
                            Id = 117,
                            BottomLeftX = 173.0,
                            BottomLeftY = 270.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2790),
                            TopRightX = 181.0,
                            TopRightY = 287.0
                        },
                        new
                        {
                            Id = 118,
                            BottomLeftX = 25.0,
                            BottomLeftY = 110.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2810),
                            TopRightX = 32.0,
                            TopRightY = 133.0
                        },
                        new
                        {
                            Id = 119,
                            BottomLeftX = 138.0,
                            BottomLeftY = 309.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2830),
                            TopRightX = 159.0,
                            TopRightY = 330.0
                        },
                        new
                        {
                            Id = 120,
                            BottomLeftX = 396.0,
                            BottomLeftY = 395.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2860),
                            TopRightX = 413.0,
                            TopRightY = 400.0
                        },
                        new
                        {
                            Id = 121,
                            BottomLeftX = 108.0,
                            BottomLeftY = 446.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2880),
                            TopRightX = 133.0,
                            TopRightY = 451.0
                        },
                        new
                        {
                            Id = 122,
                            BottomLeftX = 364.0,
                            BottomLeftY = 306.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2910),
                            TopRightX = 370.0,
                            TopRightY = 319.0
                        },
                        new
                        {
                            Id = 123,
                            BottomLeftX = 217.0,
                            BottomLeftY = 338.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2930),
                            TopRightX = 225.0,
                            TopRightY = 362.0
                        },
                        new
                        {
                            Id = 124,
                            BottomLeftX = 352.0,
                            BottomLeftY = 330.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2970),
                            TopRightX = 370.0,
                            TopRightY = 359.0
                        },
                        new
                        {
                            Id = 125,
                            BottomLeftX = 40.0,
                            BottomLeftY = 316.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(2990),
                            TopRightX = 68.0,
                            TopRightY = 345.0
                        },
                        new
                        {
                            Id = 126,
                            BottomLeftX = 185.0,
                            BottomLeftY = 454.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3020),
                            TopRightX = 208.0,
                            TopRightY = 475.0
                        },
                        new
                        {
                            Id = 127,
                            BottomLeftX = 240.0,
                            BottomLeftY = 386.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3040),
                            TopRightX = 248.0,
                            TopRightY = 412.0
                        },
                        new
                        {
                            Id = 128,
                            BottomLeftX = 149.0,
                            BottomLeftY = 238.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3070),
                            TopRightX = 162.0,
                            TopRightY = 250.0
                        },
                        new
                        {
                            Id = 129,
                            BottomLeftX = 73.0,
                            BottomLeftY = 490.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3090),
                            TopRightX = 100.0,
                            TopRightY = 498.0
                        },
                        new
                        {
                            Id = 130,
                            BottomLeftX = 221.0,
                            BottomLeftY = 397.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3120),
                            TopRightX = 244.0,
                            TopRightY = 405.0
                        },
                        new
                        {
                            Id = 131,
                            BottomLeftX = 337.0,
                            BottomLeftY = 245.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3140),
                            TopRightX = 365.0,
                            TopRightY = 257.0
                        },
                        new
                        {
                            Id = 132,
                            BottomLeftX = 64.0,
                            BottomLeftY = 270.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3160),
                            TopRightX = 80.0,
                            TopRightY = 285.0
                        },
                        new
                        {
                            Id = 133,
                            BottomLeftX = 499.0,
                            BottomLeftY = 272.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3190),
                            TopRightX = 515.0,
                            TopRightY = 287.0
                        },
                        new
                        {
                            Id = 134,
                            BottomLeftX = 38.0,
                            BottomLeftY = 40.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3210),
                            TopRightX = 45.0,
                            TopRightY = 57.0
                        },
                        new
                        {
                            Id = 135,
                            BottomLeftX = 369.0,
                            BottomLeftY = 1.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3230),
                            TopRightX = 388.0,
                            TopRightY = 28.0
                        },
                        new
                        {
                            Id = 136,
                            BottomLeftX = 437.0,
                            BottomLeftY = 85.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3260),
                            TopRightX = 446.0,
                            TopRightY = 112.0
                        },
                        new
                        {
                            Id = 137,
                            BottomLeftX = 147.0,
                            BottomLeftY = 13.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3280),
                            TopRightX = 173.0,
                            TopRightY = 36.0
                        },
                        new
                        {
                            Id = 138,
                            BottomLeftX = 234.0,
                            BottomLeftY = 189.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3310),
                            TopRightX = 241.0,
                            TopRightY = 194.0
                        },
                        new
                        {
                            Id = 139,
                            BottomLeftX = 118.0,
                            BottomLeftY = 373.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3330),
                            TopRightX = 147.0,
                            TopRightY = 401.0
                        },
                        new
                        {
                            Id = 140,
                            BottomLeftX = 199.0,
                            BottomLeftY = 492.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3350),
                            TopRightX = 221.0,
                            TopRightY = 514.0
                        },
                        new
                        {
                            Id = 141,
                            BottomLeftX = 429.0,
                            BottomLeftY = 5.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3380),
                            TopRightX = 440.0,
                            TopRightY = 26.0
                        },
                        new
                        {
                            Id = 142,
                            BottomLeftX = 444.0,
                            BottomLeftY = 257.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3400),
                            TopRightX = 468.0,
                            TopRightY = 264.0
                        },
                        new
                        {
                            Id = 143,
                            BottomLeftX = 135.0,
                            BottomLeftY = 380.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3430),
                            TopRightX = 146.0,
                            TopRightY = 407.0
                        },
                        new
                        {
                            Id = 144,
                            BottomLeftX = 207.0,
                            BottomLeftY = 433.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3450),
                            TopRightX = 217.0,
                            TopRightY = 444.0
                        },
                        new
                        {
                            Id = 145,
                            BottomLeftX = 136.0,
                            BottomLeftY = 337.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3480),
                            TopRightX = 145.0,
                            TopRightY = 347.0
                        },
                        new
                        {
                            Id = 146,
                            BottomLeftX = 53.0,
                            BottomLeftY = 376.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3500),
                            TopRightX = 64.0,
                            TopRightY = 401.0
                        },
                        new
                        {
                            Id = 147,
                            BottomLeftX = 393.0,
                            BottomLeftY = 74.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3520),
                            TopRightX = 412.0,
                            TopRightY = 103.0
                        },
                        new
                        {
                            Id = 148,
                            BottomLeftX = 162.0,
                            BottomLeftY = 119.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3550),
                            TopRightX = 176.0,
                            TopRightY = 146.0
                        },
                        new
                        {
                            Id = 149,
                            BottomLeftX = 183.0,
                            BottomLeftY = 222.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3570),
                            TopRightX = 194.0,
                            TopRightY = 237.0
                        },
                        new
                        {
                            Id = 150,
                            BottomLeftX = 393.0,
                            BottomLeftY = 173.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3600),
                            TopRightX = 406.0,
                            TopRightY = 193.0
                        },
                        new
                        {
                            Id = 151,
                            BottomLeftX = 408.0,
                            BottomLeftY = 48.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3620),
                            TopRightX = 431.0,
                            TopRightY = 53.0
                        },
                        new
                        {
                            Id = 152,
                            BottomLeftX = 415.0,
                            BottomLeftY = 191.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3640),
                            TopRightX = 434.0,
                            TopRightY = 201.0
                        },
                        new
                        {
                            Id = 153,
                            BottomLeftX = 21.0,
                            BottomLeftY = 222.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3670),
                            TopRightX = 32.0,
                            TopRightY = 246.0
                        },
                        new
                        {
                            Id = 154,
                            BottomLeftX = 480.0,
                            BottomLeftY = 475.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3690),
                            TopRightX = 485.0,
                            TopRightY = 491.0
                        },
                        new
                        {
                            Id = 155,
                            BottomLeftX = 316.0,
                            BottomLeftY = 470.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3720),
                            TopRightX = 344.0,
                            TopRightY = 491.0
                        },
                        new
                        {
                            Id = 156,
                            BottomLeftX = 129.0,
                            BottomLeftY = 138.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3740),
                            TopRightX = 134.0,
                            TopRightY = 160.0
                        },
                        new
                        {
                            Id = 157,
                            BottomLeftX = 393.0,
                            BottomLeftY = 480.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3760),
                            TopRightX = 419.0,
                            TopRightY = 508.0
                        },
                        new
                        {
                            Id = 158,
                            BottomLeftX = 267.0,
                            BottomLeftY = 66.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3790),
                            TopRightX = 283.0,
                            TopRightY = 87.0
                        },
                        new
                        {
                            Id = 159,
                            BottomLeftX = 81.0,
                            BottomLeftY = 131.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3810),
                            TopRightX = 103.0,
                            TopRightY = 153.0
                        },
                        new
                        {
                            Id = 160,
                            BottomLeftX = 283.0,
                            BottomLeftY = 462.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3840),
                            TopRightX = 312.0,
                            TopRightY = 479.0
                        },
                        new
                        {
                            Id = 161,
                            BottomLeftX = 174.0,
                            BottomLeftY = 302.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3860),
                            TopRightX = 184.0,
                            TopRightY = 321.0
                        },
                        new
                        {
                            Id = 162,
                            BottomLeftX = 100.0,
                            BottomLeftY = 95.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3880),
                            TopRightX = 127.0,
                            TopRightY = 111.0
                        },
                        new
                        {
                            Id = 163,
                            BottomLeftX = 233.0,
                            BottomLeftY = 208.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3910),
                            TopRightX = 241.0,
                            TopRightY = 224.0
                        },
                        new
                        {
                            Id = 164,
                            BottomLeftX = 481.0,
                            BottomLeftY = 25.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3930),
                            TopRightX = 491.0,
                            TopRightY = 45.0
                        },
                        new
                        {
                            Id = 165,
                            BottomLeftX = 393.0,
                            BottomLeftY = 413.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3960),
                            TopRightX = 414.0,
                            TopRightY = 432.0
                        },
                        new
                        {
                            Id = 166,
                            BottomLeftX = 482.0,
                            BottomLeftY = 57.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(3980),
                            TopRightX = 493.0,
                            TopRightY = 73.0
                        },
                        new
                        {
                            Id = 167,
                            BottomLeftX = 2.0,
                            BottomLeftY = 427.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4010),
                            TopRightX = 8.0,
                            TopRightY = 447.0
                        },
                        new
                        {
                            Id = 168,
                            BottomLeftX = 174.0,
                            BottomLeftY = 56.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4030),
                            TopRightX = 195.0,
                            TopRightY = 85.0
                        },
                        new
                        {
                            Id = 169,
                            BottomLeftX = 242.0,
                            BottomLeftY = 428.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4050),
                            TopRightX = 252.0,
                            TopRightY = 455.0
                        },
                        new
                        {
                            Id = 170,
                            BottomLeftX = 58.0,
                            BottomLeftY = 322.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4080),
                            TopRightX = 77.0,
                            TopRightY = 339.0
                        },
                        new
                        {
                            Id = 171,
                            BottomLeftX = 381.0,
                            BottomLeftY = 13.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4170),
                            TopRightX = 408.0,
                            TopRightY = 37.0
                        },
                        new
                        {
                            Id = 172,
                            BottomLeftX = 277.0,
                            BottomLeftY = 463.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4200),
                            TopRightX = 293.0,
                            TopRightY = 479.0
                        },
                        new
                        {
                            Id = 173,
                            BottomLeftX = 246.0,
                            BottomLeftY = 379.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4220),
                            TopRightX = 259.0,
                            TopRightY = 387.0
                        },
                        new
                        {
                            Id = 174,
                            BottomLeftX = 477.0,
                            BottomLeftY = 28.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4240),
                            TopRightX = 493.0,
                            TopRightY = 45.0
                        },
                        new
                        {
                            Id = 175,
                            BottomLeftX = 237.0,
                            BottomLeftY = 361.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4270),
                            TopRightX = 263.0,
                            TopRightY = 367.0
                        },
                        new
                        {
                            Id = 176,
                            BottomLeftX = 305.0,
                            BottomLeftY = 441.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4290),
                            TopRightX = 314.0,
                            TopRightY = 456.0
                        },
                        new
                        {
                            Id = 177,
                            BottomLeftX = 461.0,
                            BottomLeftY = 450.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4320),
                            TopRightX = 469.0,
                            TopRightY = 457.0
                        },
                        new
                        {
                            Id = 178,
                            BottomLeftX = 471.0,
                            BottomLeftY = 234.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4340),
                            TopRightX = 479.0,
                            TopRightY = 245.0
                        },
                        new
                        {
                            Id = 179,
                            BottomLeftX = 110.0,
                            BottomLeftY = 3.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4360),
                            TopRightX = 138.0,
                            TopRightY = 32.0
                        },
                        new
                        {
                            Id = 180,
                            BottomLeftX = 105.0,
                            BottomLeftY = 352.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4390),
                            TopRightX = 130.0,
                            TopRightY = 377.0
                        },
                        new
                        {
                            Id = 181,
                            BottomLeftX = 25.0,
                            BottomLeftY = 441.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4410),
                            TopRightX = 43.0,
                            TopRightY = 465.0
                        },
                        new
                        {
                            Id = 182,
                            BottomLeftX = 17.0,
                            BottomLeftY = 256.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4440),
                            TopRightX = 45.0,
                            TopRightY = 275.0
                        },
                        new
                        {
                            Id = 183,
                            BottomLeftX = 419.0,
                            BottomLeftY = 85.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4460),
                            TopRightX = 437.0,
                            TopRightY = 93.0
                        },
                        new
                        {
                            Id = 184,
                            BottomLeftX = 341.0,
                            BottomLeftY = 109.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4480),
                            TopRightX = 355.0,
                            TopRightY = 137.0
                        },
                        new
                        {
                            Id = 185,
                            BottomLeftX = 303.0,
                            BottomLeftY = 337.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4510),
                            TopRightX = 325.0,
                            TopRightY = 364.0
                        },
                        new
                        {
                            Id = 186,
                            BottomLeftX = 197.0,
                            BottomLeftY = 340.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4530),
                            TopRightX = 211.0,
                            TopRightY = 356.0
                        },
                        new
                        {
                            Id = 187,
                            BottomLeftX = 396.0,
                            BottomLeftY = 261.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4560),
                            TopRightX = 421.0,
                            TopRightY = 290.0
                        },
                        new
                        {
                            Id = 188,
                            BottomLeftX = 57.0,
                            BottomLeftY = 476.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4580),
                            TopRightX = 79.0,
                            TopRightY = 492.0
                        },
                        new
                        {
                            Id = 189,
                            BottomLeftX = 204.0,
                            BottomLeftY = 270.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4610),
                            TopRightX = 224.0,
                            TopRightY = 295.0
                        },
                        new
                        {
                            Id = 190,
                            BottomLeftX = 144.0,
                            BottomLeftY = 459.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4630),
                            TopRightX = 156.0,
                            TopRightY = 471.0
                        },
                        new
                        {
                            Id = 191,
                            BottomLeftX = 68.0,
                            BottomLeftY = 265.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4650),
                            TopRightX = 79.0,
                            TopRightY = 285.0
                        },
                        new
                        {
                            Id = 192,
                            BottomLeftX = 127.0,
                            BottomLeftY = 490.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4680),
                            TopRightX = 138.0,
                            TopRightY = 496.0
                        },
                        new
                        {
                            Id = 193,
                            BottomLeftX = 239.0,
                            BottomLeftY = 288.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4700),
                            TopRightX = 262.0,
                            TopRightY = 316.0
                        },
                        new
                        {
                            Id = 194,
                            BottomLeftX = 422.0,
                            BottomLeftY = 22.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4730),
                            TopRightX = 444.0,
                            TopRightY = 30.0
                        },
                        new
                        {
                            Id = 195,
                            BottomLeftX = 69.0,
                            BottomLeftY = 386.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4750),
                            TopRightX = 74.0,
                            TopRightY = 396.0
                        },
                        new
                        {
                            Id = 196,
                            BottomLeftX = 248.0,
                            BottomLeftY = 417.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4780),
                            TopRightX = 262.0,
                            TopRightY = 423.0
                        },
                        new
                        {
                            Id = 197,
                            BottomLeftX = 475.0,
                            BottomLeftY = 237.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4800),
                            TopRightX = 483.0,
                            TopRightY = 244.0
                        },
                        new
                        {
                            Id = 198,
                            BottomLeftX = 173.0,
                            BottomLeftY = 68.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4820),
                            TopRightX = 198.0,
                            TopRightY = 84.0
                        },
                        new
                        {
                            Id = 199,
                            BottomLeftX = 269.0,
                            BottomLeftY = 176.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4850),
                            TopRightX = 288.0,
                            TopRightY = 188.0
                        },
                        new
                        {
                            Id = 200,
                            BottomLeftX = 484.0,
                            BottomLeftY = 372.0,
                            CreateDate = new DateTime(2023, 11, 5, 20, 45, 13, 207, DateTimeKind.Utc).AddTicks(4870),
                            TopRightX = 491.0,
                            TopRightY = 380.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
